### ISSUE TITLE
Clarify this is for native code debugging

### ISSUE THREAD

**Issue by drewnoakes** [Flast/msgpack-vs-visualizer#1]
I've created a similar VS debugger visualiser for managed .NET code.

https://github.com/drewnoakes/msgpack-vs-visualiser-dotnet

It might be worth mentioning in your README that this repo applies to native code debugging. I'll reference this project from mine too.

**Comment by Flast** [comment]
Thanks for the reporting, and sorry for late reply, I totally thought I resolved this issue.
